# Calculate MetaTrader 5 History Report Factors
Author: Mohamed Abbas El Kayal

In [457]:
# import required libraries

import MetaTrader5 as mt5
import pandas as pd
import plotly.express as px
import numpy as np
import datetime
from IPython.display import display
from datetime import datetime

In [458]:
# connect to MetaTrader5 as mt5
mt5.initialize()

True

In [459]:
from_date=datetime(2020,1,1)
to_date=datetime.now()
trade_deals=mt5.history_deals_get(from_date, to_date)
display(trade_deals)

(TradeDeal(ticket=3815102040, order=0, time=1702671948, time_msc=1702671948860, type=2, entry=0, magic=0, position_id=0, reason=0, volume=0.0, price=0.0, commission=0.0, swap=0.0, profit=10000.0, fee=0.0, symbol='', comment='', external_id=''),
 TradeDeal(ticket=3815102992, order=3818161067, time=1702676120, time_msc=1702676120199, type=0, entry=0, magic=100, position_id=3818161067, reason=3, volume=0.01, price=1.08951, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815102993, order=3818161068, time=1702676120, time_msc=1702676120451, type=1, entry=0, magic=100, position_id=3818161068, reason=3, volume=0.02, price=1.08931, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815102995, order=3818161070, time=1702676133, time_msc=1702676133795, type=0, entry=1, magic=0, position_id=3818161068, reason=0, volume=0.02, price=1.08952, commission=0.0, swap=0.0, profit=-0.42, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815102996, order=3818161071, time=1702676134, time_msc=1702676134243, type=1, entry=1, magic=0, position_id=3818161067, reason=0, volume=0.01, price=1.08932, commission=0.0, swap=0.0, profit=-0.19, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103003, order=3818161079, time=1702676215, time_msc=1702676215092, type=0, entry=0, magic=100, position_id=3818161079, reason=3, volume=0.01, price=1.26867, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='GBPUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103004, order=3818161080, time=1702676215, time_msc=1702676215248, type=1, entry=0, magic=100, position_id=3818161080, reason=3, volume=0.02, price=1.08929, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103006, order=3818161083, time=1702676265, time_msc=1702676265271, type=0, entry=1, magic=0, position_id=3818161080, reason=0, volume=0.02, price=1.0895, commission=0.0, swap=0.0, profit=-0.42, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103007, order=3818161082, time=1702676265, time_msc=1702676265272, type=1, entry=1, magic=0, position_id=3818161079, reason=0, volume=0.01, price=1.26848, commission=0.0, swap=0.0, profit=-0.19, fee=0.0, symbol='GBPUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103039, order=3818161113, time=1702676857, time_msc=1702676857126, type=0, entry=0, magic=100, position_id=3818161113, reason=3, volume=0.01, price=1.26901, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='GBPUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103040, order=3818161114, time=1702676857, time_msc=1702676857282, type=1, entry=0, magic=100, position_id=3818161114, reason=3, volume=0.02, price=1.08948, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103041, order=3818161115, time=1702676857, time_msc=1702676857485, type=0, entry=0, magic=100, position_id=3818161115, reason=3, volume=0.01, price=1.26901, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='GBPUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103042, order=3818161116, time=1702676857, time_msc=1702676857694, type=1, entry=0, magic=100, position_id=3818161116, reason=3, volume=0.02, price=1.08948, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103045, order=3818161119, time=1702676909, time_msc=1702676909473, type=1, entry=1, magic=0, position_id=3818161113, reason=0, volume=0.01, price=1.26883, commission=0.0, swap=0.0, profit=-0.18, fee=0.0, symbol='GBPUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103046, order=3818161121, time=1702676909, time_msc=1702676909521, type=1, entry=1, magic=0, position_id=3818161115, reason=0, volume=0.01, price=1.26883, commission=0.0, swap=0.0, profit=-0.18, fee=0.0, symbol='GBPUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103047, order=3818161120, time=1702676909, time_msc=1702676909522, type=0, entry=1, magic=0, position_id=3818161114, reason=0, volume=0.02, price=1.0897, commission=0.0, swap=0.0, profit=-0.44, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103048, order=3818161122, time=1702676909, time_msc=1702676909523, type=0, entry=1, magic=0, position_id=3818161116, reason=0, volume=0.02, price=1.0897, commission=0.0, swap=0.0, profit=-0.44, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103068, order=3818161142, time=1702677060, time_msc=1702677060039, type=0, entry=0, magic=100, position_id=3818161142, reason=3, volume=0.01, price=1.26895, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='GBPUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103069, order=3818161143, time=1702677060, time_msc=1702677060236, type=1, entry=0, magic=100, position_id=3818161143, reason=3, volume=0.02, price=1.08948, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103070, order=3818161144, time=1702677060, time_msc=1702677060413, type=0, entry=0, magic=100, position_id=3818161144, reason=3, volume=0.01, price=1.45714, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURCAD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815103087, order=3818161161, time=1702677117, time_msc=1702677117199, type=1, entry=1, magic=0, position_id=3818161142, reason=0, volume=0.01, price=1.26896, commission=0.0, swap=0.0, profit=0.01, fee=0.0, symbol='GBPUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103088, order=3818161162, time=1702677117, time_msc=1702677117266, type=0, entry=1, magic=0, position_id=3818161143, reason=0, volume=0.02, price=1.08981, commission=0.0, swap=0.0, profit=-0.66, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815103089, order=3818161163, time=1702677117, time_msc=1702677117267, type=1, entry=1, magic=0, position_id=3818161144, reason=0, volume=0.01, price=1.45668, commission=0.0, swap=0.0, profit=-0.34, fee=0.0, symbol='EURCAD', comment='', external_id=''),
 TradeDeal(ticket=3815153021, order=3818211059, time=1703245142, time_msc=1703245142262, type=0, entry=0, magic=100, position_id=3818211059, reason=3, volume=0.01, price=1.27035, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='GBPUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153022, order=3818211060, time=1703245142, time_msc=1703245142416, type=1, entry=0, magic=100, position_id=3818211060, reason=3, volume=0.02, price=1.10106, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153023, order=3818211061, time=1703245142, time_msc=1703245142570, type=0, entry=0, magic=100, position_id=3818211061, reason=3, volume=0.01, price=1.46211, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURCAD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153025, order=3818211063, time=1703245153, time_msc=1703245153312, type=0, entry=1, magic=0, position_id=3818211060, reason=0, volume=0.02, price=1.10126, commission=0.0, swap=0.0, profit=-0.4, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815153026, order=3818211064, time=1703245154, time_msc=1703245154625, type=1, entry=1, magic=0, position_id=3818211059, reason=0, volume=0.01, price=1.27022, commission=0.0, swap=0.0, profit=-0.13, fee=0.0, symbol='GBPUSD', comment='', external_id=''),
 TradeDeal(ticket=3815153027, order=3818211065, time=1703245156, time_msc=1703245156135, type=1, entry=1, magic=0, position_id=3818211061, reason=0, volume=0.01, price=1.46167, commission=0.0, swap=0.0, profit=-0.33, fee=0.0, symbol='EURCAD', comment='', external_id=''),
 TradeDeal(ticket=3815153085, order=3818211131, time=1703245659, time_msc=1703245659703, type=0, entry=0, magic=100, position_id=3818211131, reason=3, volume=0.01, price=1.26972, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='GBPUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153086, order=3818211132, time=1703245659, time_msc=1703245659861, type=1, entry=0, magic=100, position_id=3818211132, reason=3, volume=0.02, price=1.10087, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153087, order=3818211133, time=1703245660, time_msc=1703245660016, type=0, entry=0, magic=100, position_id=3818211133, reason=3, volume=0.01, price=1.46165, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURCAD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153090, order=3818211136, time=1703245663, time_msc=1703245663348, type=1, entry=1, magic=0, position_id=3818211131, reason=0, volume=0.01, price=1.2696, commission=0.0, swap=0.0, profit=-0.12, fee=0.0, symbol='GBPUSD', comment='', external_id=''),
 TradeDeal(ticket=3815153091, order=3818211137, time=1703245663, time_msc=1703245663877, type=0, entry=1, magic=0, position_id=3818211132, reason=0, volume=0.02, price=1.10107, commission=0.0, swap=0.0, profit=-0.4, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815153092, order=3818211138, time=1703245664, time_msc=1703245664437, type=1, entry=1, magic=0, position_id=3818211133, reason=0, volume=0.01, price=1.46113, commission=0.0, swap=0.0, profit=-0.39, fee=0.0, symbol='EURCAD', comment='', external_id=''),
 TradeDeal(ticket=3815153169, order=3818211287, time=1703246475, time_msc=1703246475533, type=0, entry=0, magic=100, position_id=3818211287, reason=3, volume=0.01, price=0.85573, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='USDCHF', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153171, order=3818211289, time=1703246517, time_msc=1703246517917, type=0, entry=0, magic=100, position_id=3818211289, reason=3, volume=0.01, price=0.85565, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='USDCHF', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153176, order=3818211294, time=1703246579, time_msc=1703246579633, type=0, entry=0, magic=100, position_id=3818211294, reason=3, volume=0.01, price=0.85565, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='USDCHF', comment='python script op', external_id=''),
 TradeDeal(ticket=3815153177, order=3818211295, time=1703246598, time_msc=1703246598704, type=1, entry=1, magic=0, position_id=3818211294, reason=0, volume=0.01, price=0.85551, commission=0.0, swap=0.0, profit=-0.16, fee=0.0, symbol='USDCHF', comment='', external_id=''),
 TradeDeal(ticket=3815153178, order=3818211296, time=1703246599, time_msc=1703246599275, type=1, entry=1, magic=0, position_id=3818211289, reason=0, volume=0.01, price=0.85551, commission=0.0, swap=0.0, profit=-0.16, fee=0.0, symbol='USDCHF', comment='', external_id=''),
 TradeDeal(ticket=3815153179, order=3818211297, time=1703246599, time_msc=1703246599812, type=1, entry=1, magic=0, position_id=3818211287, reason=0, volume=0.01, price=0.85551, commission=0.0, swap=0.0, profit=-0.26, fee=0.0, symbol='USDCHF', comment='', external_id=''),
 TradeDeal(ticket=3815155282, order=3818213499, time=1703254695, time_msc=1703254695964, type=0, entry=0, magic=100, position_id=3818213499, reason=3, volume=0.01, price=0.85372, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='USDCHF', comment='python script op', external_id=''),
 TradeDeal(ticket=3815155284, order=3818213501, time=1703254700, time_msc=1703254700543, type=1, entry=1, magic=0, position_id=3818213499, reason=0, volume=0.01, price=0.85357, commission=0.0, swap=0.0, profit=-0.18, fee=0.0, symbol='USDCHF', comment='', external_id=''),
 TradeDeal(ticket=3815155325, order=3818213542, time=1703255050, time_msc=1703255050422, type=0, entry=0, magic=100, position_id=3818213542, reason=3, volume=0.01, price=0.85353, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='USDCHF', comment='python script op', external_id=''),
 TradeDeal(ticket=3815155336, order=3818213551, time=1703255093, time_msc=1703255093974, type=1, entry=1, magic=0, position_id=3818213542, reason=0, volume=0.01, price=0.85323, commission=0.0, swap=0.0, profit=-0.35, fee=0.0, symbol='USDCHF', comment='', external_id=''),
 TradeDeal(ticket=3815155345, order=3818213559, time=1703255121, time_msc=1703255121794, type=0, entry=0, magic=100, position_id=3818213559, reason=3, volume=0.01, price=0.85342, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='USDCHF', comment='python script op', external_id=''),
 TradeDeal(ticket=3815155665, order=3818213884, time=1703255596, time_msc=1703255596411, type=1, entry=1, magic=0, position_id=3818213559, reason=0, volume=0.01, price=0.85316, commission=0.0, swap=0.0, profit=-0.3, fee=0.0, symbol='USDCHF', comment='', external_id=''),
 TradeDeal(ticket=3815156630, order=3818214856, time=1703256082, time_msc=1703256082337, type=0, entry=0, magic=100, position_id=3818214856, reason=3, volume=0.01, price=1.1033, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156640, order=3818214867, time=1703256139, time_msc=1703256139694, type=0, entry=0, magic=100, position_id=3818214867, reason=3, volume=0.01, price=1.10297, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156667, order=3818214896, time=1703256322, time_msc=1703256322711, type=0, entry=0, magic=100, position_id=3818214896, reason=3, volume=0.01, price=1.1029, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156668, order=3818214897, time=1703256322, time_msc=1703256322870, type=0, entry=0, magic=100, position_id=3818214897, reason=3, volume=0.03, price=1.1029, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156678, order=3818214905, time=1703256365, time_msc=1703256365399, type=0, entry=0, magic=100, position_id=3818214905, reason=3, volume=0.01, price=1.10268, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156679, order=3818214906, time=1703256365, time_msc=1703256365552, type=0, entry=0, magic=100, position_id=3818214906, reason=3, volume=0.03, price=1.10268, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156702, order=3818214928, time=1703256385, time_msc=1703256385764, type=0, entry=0, magic=100, position_id=3818214928, reason=3, volume=0.01, price=1.10261, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156703, order=3818214929, time=1703256385, time_msc=1703256385922, type=0, entry=0, magic=100, position_id=3818214929, reason=3, volume=0.03, price=1.10261, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156707, order=3818214933, time=1703256397, time_msc=1703256397918, type=1, entry=1, magic=0, position_id=3818214856, reason=0, volume=0.01, price=1.10237, commission=0.0, swap=0.0, profit=-0.93, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156708, order=3818214934, time=1703256397, time_msc=1703256397966, type=1, entry=1, magic=0, position_id=3818214867, reason=0, volume=0.01, price=1.10237, commission=0.0, swap=0.0, profit=-0.6, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156709, order=3818214935, time=1703256397, time_msc=1703256397966, type=1, entry=1, magic=0, position_id=3818214896, reason=0, volume=0.01, price=1.10237, commission=0.0, swap=0.0, profit=-0.53, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156710, order=3818214936, time=1703256397, time_msc=1703256397967, type=1, entry=1, magic=0, position_id=3818214897, reason=0, volume=0.03, price=1.10237, commission=0.0, swap=0.0, profit=-1.5899999999999999, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156711, order=3818214938, time=1703256397, time_msc=1703256397967, type=1, entry=1, magic=0, position_id=3818214906, reason=0, volume=0.03, price=1.10237, commission=0.0, swap=0.0, profit=-0.93, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156712, order=3818214937, time=1703256397, time_msc=1703256397967, type=1, entry=1, magic=0, position_id=3818214905, reason=0, volume=0.01, price=1.10237, commission=0.0, swap=0.0, profit=-0.31, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156713, order=3818214939, time=1703256398, time_msc=1703256398359, type=1, entry=1, magic=0, position_id=3818214928, reason=0, volume=0.01, price=1.10237, commission=0.0, swap=0.0, profit=-0.24, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156714, order=3818214940, time=1703256398, time_msc=1703256398359, type=1, entry=1, magic=0, position_id=3818214929, reason=0, volume=0.03, price=1.10237, commission=0.0, swap=0.0, profit=-0.72, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156755, order=3818214983, time=1703256461, time_msc=1703256461813, type=0, entry=0, magic=100, position_id=3818214983, reason=3, volume=0.01, price=1.10248, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156756, order=3818214984, time=1703256461, time_msc=1703256461968, type=0, entry=0, magic=100, position_id=3818214984, reason=3, volume=0.03, price=1.27181, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='GBPUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815156777, order=3818215004, time=1703256491, time_msc=1703256491500, type=1, entry=1, magic=0, position_id=3818214984, reason=0, volume=0.03, price=1.27154, commission=0.0, swap=0.0, profit=-0.81, fee=0.0, symbol='GBPUSD', comment='', external_id=''),
 TradeDeal(ticket=3815156778, order=3818215003, time=1703256491, time_msc=1703256491500, type=1, entry=1, magic=0, position_id=3818214983, reason=0, volume=0.01, price=1.10224, commission=0.0, swap=0.0, profit=-0.24, fee=0.0, symbol='EURUSD', comment='', external_id=''),
 TradeDeal(ticket=3815157000, order=3818215218, time=1703257115, time_msc=1703257115719, type=0, entry=0, magic=100, position_id=3818215218, reason=3, volume=0.01, price=1.10179, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815157001, order=3818215219, time=1703257115, time_msc=1703257115879, type=1, entry=0, magic=100, position_id=3818215219, reason=3, volume=0.03, price=1.10157, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815157003, order=3818215221, time=1703257135, time_msc=1703257135557, type=0, entry=0, magic=100, position_id=3818215221, reason=3, volume=0.01, price=1.10191, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),
 TradeDeal(ticket=3815157004, order=3818215222, time=1703257135, time_msc=1703257135711, type=1, entry=0, magic=100, position_id=3818215222, reason=3, volume=0.03, price=1.10171, commission=0.0, swap=0.0, profit=0.0, fee=0.0, symbol='EURUSD', comment='python script op', external_id=''),

In [460]:
# display these positions as a table using pandas.DataFrame
deals = pd.DataFrame(list(trade_deals), columns=trade_deals[0]._asdict().keys())

deals

,ticket,order,time,time_msc,type,entry,magic,position_id,reason,volume,price,commission,swap,profit,fee,symbol,comment,external_id
0,3815102040,0,1702671948,1702671948860,2,0,0,0,0,0.00,0.00000,0.0,0.00,10000.00,0.0,,,
1,3815102992,3818161067,1702676120,1702676120199,0,0,100,3818161067,3,0.01,1.08951,0.0,0.00,0.00,0.0,EURUSD,python script op,
2,3815102993,3818161068,1702676120,1702676120451,1,0,100,3818161068,3,0.02,1.08931,0.0,0.00,0.00,0.0,EURUSD,python script op,
3,3815102995,3818161070,1702676133,1702676133795,0,1,0,3818161068,0,0.02,1.08952,0.0,0.00,-0.42,0.0,EURUSD,,
4,3815102996,3818161071,1702676134,1702676134243,1,1,0,3818161067,0,0.01,1.08932,0.0,0.00,-0.19,0.0,EURUSD,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,3815162740,3818220981,1703270451,1703270451761,0,1,100,3818220793,3,0.05,1.10175,0.0,0.00,-2.15,0.0,EURUSD,python script cl,
131,3815162741,3818220982,1703270451,1703270451918,1,1,100,3818220794,3,0.01,1.10155,0.0,0.00,0.04,0.0,EURUSD,python script cl,
132,3815162742,3818220983,1703270452,1703270452075,0,1,100,3818220795,3,0.05,1.10175,0.0,0.00,-2.20,0.0,EURUSD,python script cl,
133,3815202141,3818259693,1703796458,1703796458900,0,0,100,3818259693,3,0.01,1.10590,0.0,0.00,0.00,0.0,EURUSD,python script op,
134,3815208349,3818265725,1703849490,1703849490700,1,1,0,3818259693,0,0.01,1.10489,0.0,-0.06,-1.01,0.0,EURUSD,,

In [461]:
# re-factor data frame
# convert time in history to human readable time format
deals['time'] = pd.to_datetime(deals['time'], unit='s')

deals

,ticket,order,time,time_msc,type,entry,magic,position_id,reason,volume,price,commission,swap,profit,fee,symbol,comment,external_id
0,3815102040,0,2023-12-15 20:25:48,1702671948860,2,0,0,0,0,0.00,0.00000,0.0,0.00,10000.00,0.0,,,
1,3815102992,3818161067,2023-12-15 21:35:20,1702676120199,0,0,100,3818161067,3,0.01,1.08951,0.0,0.00,0.00,0.0,EURUSD,python script op,
2,3815102993,3818161068,2023-12-15 21:35:20,1702676120451,1,0,100,3818161068,3,0.02,1.08931,0.0,0.00,0.00,0.0,EURUSD,python script op,
3,3815102995,3818161070,2023-12-15 21:35:33,1702676133795,0,1,0,3818161068,0,0.02,1.08952,0.0,0.00,-0.42,0.0,EURUSD,,
4,3815102996,3818161071,2023-12-15 21:35:34,1702676134243,1,1,0,3818161067,0,0.01,1.08932,0.0,0.00,-0.19,0.0,EURUSD,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,3815162740,3818220981,2023-12-22 18:40:51,1703270451761,0,1,100,3818220793,3,0.05,1.10175,0.0,0.00,-2.15,0.0,EURUSD,python script cl,
131,3815162741,3818220982,2023-12-22 18:40:51,1703270451918,1,1,100,3818220794,3,0.01,1.10155,0.0,0.00,0.04,0.0,EURUSD,python script cl,
132,3815162742,3818220983,2023-12-22 18:40:52,1703270452075,0,1,100,3818220795,3,0.05,1.10175,0.0,0.00,-2.20,0.0,EURUSD,python script cl,
133,3815202141,3818259693,2023-12-28 20:47:38,1703796458900,0,0,100,3818259693,3,0.01,1.10590,0.0,0.00,0.00,0.0,EURUSD,python script op,
134,3815208349,3818265725,2023-12-29 11:31:30,1703849490700,1,1,0,3818259693,0,0.01,1.10489,0.0,-0.06,-1.01,0.0,EURUSD,,

In [462]:
#  Get Columns Titles to check Existing Columns
titles = deals.columns

for title in titles:
 print(title)

ticket
order
time
time_msc
type
entry
magic
position_id
reason
volume
price
commission
swap
profit
fee
symbol
comment
external_id

In [463]:
# drop un-usable columns
deals.drop(['ticket', 
            'order',  
            'time_msc', 
            'entry', 
            'comment', 
            'external_id'
            ], 
           axis=1, inplace=True)

deals

,time,type,magic,position_id,reason,volume,price,commission,swap,profit,fee,symbol
0,2023-12-15 20:25:48,2,0,0,0,0.00,0.00000,0.0,0.00,10000.00,0.0,
1,2023-12-15 21:35:20,0,100,3818161067,3,0.01,1.08951,0.0,0.00,0.00,0.0,EURUSD
2,2023-12-15 21:35:20,1,100,3818161068,3,0.02,1.08931,0.0,0.00,0.00,0.0,EURUSD
3,2023-12-15 21:35:33,0,0,3818161068,0,0.02,1.08952,0.0,0.00,-0.42,0.0,EURUSD
4,2023-12-15 21:35:34,1,0,3818161067,0,0.01,1.08932,0.0,0.00,-0.19,0.0,EURUSD
...,...,...,...,...,...,...,...,...,...,...,...,...
130,2023-12-22 18:40:51,0,100,3818220793,3,0.05,1.10175,0.0,0.00,-2.15,0.0,EURUSD
131,2023-12-22 18:40:51,1,100,3818220794,3,0.01,1.10155,0.0,0.00,0.04,0.0,EURUSD
132,2023-12-22 18:40:52,0,100,3818220795,3,0.05,1.10175,0.0,0.00,-2.20,0.0,EURUSD
133,2023-12-28 20:47:38,0,100,3818259693,3,0.01,1.10590,0.0,0.00,0.00,0.0,EURUSD
134,2023-12-29 11:31:30,1,0,3818259693,0,0.01,1.10489,0.0,-0.06,-1.01,0.0,EURUSD

In [464]:
# collect positions open status

# copy dataframe (deals) to new dataframe (deals_open)
deals_open = deals.copy()

# separate positions open status in separated dataframe 
deals_open = deals_open.drop_duplicates(subset=["position_id"], keep="first")

#  drop un-usable columns in dataframe (deals_open)
deals_open.drop(['type', 
                'commission',  
                'swap', 
                'profit', 
                'fee',
                ], 
               axis=1, inplace=True)

# add "open_" to each column name
# deals_open = deals_open.add_prefix('open_')

# add "open_" to each column name except 'position_id'
# deals_open.columns = deals_open.columns.map(lambda x : x+'_open' if x !='position_id' else x)

# add "open_" to each specific columns name
deals_open.columns = ['open_' + col if col in ['time', 'price'] else col for col in deals_open.columns]

deals_open

,open_time,magic,position_id,reason,volume,open_price,symbol
0,2023-12-15 20:25:48,0,0,0,0.00,0.00000,
1,2023-12-15 21:35:20,100,3818161067,3,0.01,1.08951,EURUSD
2,2023-12-15 21:35:20,100,3818161068,3,0.02,1.08931,EURUSD
5,2023-12-15 21:36:55,100,3818161079,3,0.01,1.26867,GBPUSD
6,2023-12-15 21:36:55,100,3818161080,3,0.02,1.08929,EURUSD
...,...,...,...,...,...,...,...
123,2023-12-22 18:15:49,100,3818220792,3,0.01,1.10155,EURUSD
124,2023-12-22 18:15:49,100,3818220793,3,0.05,1.10132,EURUSD
125,2023-12-22 18:16:29,100,3818220794,3,0.01,1.10151,EURUSD
126,2023-12-22 18:16:29,100,3818220795,3,0.05,1.10131,EURUSD
133,2023-12-28 20:47:38,100,3818259693,3,0.01,1.10590,EURUSD

In [465]:
# collect positions close status

# copy dataframe (deals) to new dataframe (deals_close)
deals_close = deals.copy()

# separate positions close status in separated dataframe 
deals_close = deals_close.drop_duplicates(subset=["position_id"], keep="last")

#  drop un-usable columns in dataframe (deals_open)
deals_close.drop(['magic',
                'reason',
                'volume',
                'symbol',
                ], 
               axis=1, inplace=True)

# add "close_" to each column name
# deals_close = deals_close.add_prefix('close_')

# add "close_" to each column name except 'position_id'
# deals_close.columns = deals_close.columns.map(lambda x : x+'_close' if x !='position_id' else x)

# add "open_" to each specific columns name
deals_close.columns = ['close_' + col if col in ['time', 'price'] else col for col in deals_close.columns]

deals_close

,close_time,type,position_id,close_price,commission,swap,profit,fee
0,2023-12-15 20:25:48,2,0,0.00000,0.0,0.00,10000.00,0.0
3,2023-12-15 21:35:33,0,3818161068,1.08952,0.0,0.00,-0.42,0.0
4,2023-12-15 21:35:34,1,3818161067,1.08932,0.0,0.00,-0.19,0.0
7,2023-12-15 21:37:45,0,3818161080,1.08950,0.0,0.00,-0.42,0.0
8,2023-12-15 21:37:45,1,3818161079,1.26848,0.0,0.00,-0.19,0.0
...,...,...,...,...,...,...,...,...
129,2023-12-22 18:40:51,1,3818220792,1.10155,0.0,0.00,0.00,0.0
130,2023-12-22 18:40:51,0,3818220793,1.10175,0.0,0.00,-2.15,0.0
131,2023-12-22 18:40:51,1,3818220794,1.10155,0.0,0.00,0.04,0.0
132,2023-12-22 18:40:52,0,3818220795,1.10175,0.0,0.00,-2.20,0.0
134,2023-12-29 11:31:30,1,3818259693,1.10489,0.0,-0.06,-1.01,0.0

In [466]:
# merge (open & close) data frames into new dataframe (positions)

positions = deals_open.merge(deals_close, how='inner', on='position_id')

positions

,open_time,magic,position_id,reason,volume,open_price,symbol,close_time,type,close_price,commission,swap,profit,fee
0,2023-12-15 20:25:48,0,0,0,0.00,0.00000,,2023-12-15 20:25:48,2,0.00000,0.0,0.00,10000.00,0.0
1,2023-12-15 21:35:20,100,3818161067,3,0.01,1.08951,EURUSD,2023-12-15 21:35:34,1,1.08932,0.0,0.00,-0.19,0.0
2,2023-12-15 21:35:20,100,3818161068,3,0.02,1.08931,EURUSD,2023-12-15 21:35:33,0,1.08952,0.0,0.00,-0.42,0.0
3,2023-12-15 21:36:55,100,3818161079,3,0.01,1.26867,GBPUSD,2023-12-15 21:37:45,1,1.26848,0.0,0.00,-0.19,0.0
4,2023-12-15 21:36:55,100,3818161080,3,0.02,1.08929,EURUSD,2023-12-15 21:37:45,0,1.08950,0.0,0.00,-0.42,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2023-12-22 18:15:49,100,3818220792,3,0.01,1.10155,EURUSD,2023-12-22 18:40:51,1,1.10155,0.0,0.00,0.00,0.0
63,2023-12-22 18:15:49,100,3818220793,3,0.05,1.10132,EURUSD,2023-12-22 18:40:51,0,1.10175,0.0,0.00,-2.15,0.0
64,2023-12-22 18:16:29,100,3818220794,3,0.01,1.10151,EURUSD,2023-12-22 18:40:51,1,1.10155,0.0,0.00,0.04,0.0
65,2023-12-22 18:16:29,100,3818220795,3,0.05,1.10131,EURUSD,2023-12-22 18:40:52,0,1.10175,0.0,0.00,-2.20,0.0
66,2023-12-28 20:47:38,100,3818259693,3,0.01,1.10590,EURUSD,2023-12-29 11:31:30,1,1.10489,0.0,-0.06,-1.01,0.0

In [467]:
#  Get Columns Titles to check Existing Columns
titles = positions.columns

for title in titles:
 print(title)

open_time
magic
position_id
reason
volume
open_price
symbol
close_time
type
close_price
commission
swap
profit
fee

In [468]:
# export dataframe to csv file

# create file name based on current date and time
filename = datetime.now().strftime('%Y-%m-%d-%H-%M-%S.csv')

# export dataframe to csv file
# positions.to_csv(filename)

In [469]:
# re-factor dataframe
# in column 'type' => replace 
positions['type'] = positions['type'].replace([0], 'sell')
positions['type'] = positions['type'].replace([1], 'buy')
positions['type'] = positions['type'].replace([2], 'balance')

positions

,open_time,magic,position_id,reason,volume,open_price,symbol,close_time,type,close_price,commission,swap,profit,fee
0,2023-12-15 20:25:48,0,0,0,0.00,0.00000,,2023-12-15 20:25:48,balance,0.00000,0.0,0.00,10000.00,0.0
1,2023-12-15 21:35:20,100,3818161067,3,0.01,1.08951,EURUSD,2023-12-15 21:35:34,buy,1.08932,0.0,0.00,-0.19,0.0
2,2023-12-15 21:35:20,100,3818161068,3,0.02,1.08931,EURUSD,2023-12-15 21:35:33,sell,1.08952,0.0,0.00,-0.42,0.0
3,2023-12-15 21:36:55,100,3818161079,3,0.01,1.26867,GBPUSD,2023-12-15 21:37:45,buy,1.26848,0.0,0.00,-0.19,0.0
4,2023-12-15 21:36:55,100,3818161080,3,0.02,1.08929,EURUSD,2023-12-15 21:37:45,sell,1.08950,0.0,0.00,-0.42,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2023-12-22 18:15:49,100,3818220792,3,0.01,1.10155,EURUSD,2023-12-22 18:40:51,buy,1.10155,0.0,0.00,0.00,0.0
63,2023-12-22 18:15:49,100,3818220793,3,0.05,1.10132,EURUSD,2023-12-22 18:40:51,sell,1.10175,0.0,0.00,-2.15,0.0
64,2023-12-22 18:16:29,100,3818220794,3,0.01,1.10151,EURUSD,2023-12-22 18:40:51,buy,1.10155,0.0,0.00,0.04,0.0
65,2023-12-22 18:16:29,100,3818220795,3,0.05,1.10131,EURUSD,2023-12-22 18:40:52,sell,1.10175,0.0,0.00,-2.20,0.0
66,2023-12-28 20:47:38,100,3818259693,3,0.01,1.10590,EURUSD,2023-12-29 11:31:30,buy,1.10489,0.0,-0.06,-1.01,0.0

In [470]:
# Find Initial Deposit = Initial Balance 
# deposit = starting_balance  # Use in backtest Factors
deposit = positions.iloc[0]['profit']
print('deposit = ', deposit)

deposit =  10000.0

In [471]:
positions['pnl'] = positions['profit'].cumsum()

# positions.eval('total_pnl = commission + fee + pnl')

In [472]:
# create a column with timedelta (duration_days) including days
# positions['duration_days'] = (positions.close_time - positions.open_time)

# create a column with timedelta (duration_hours) as total hours, as a float type
# positions['duration_hours'] = (positions.close_time - positions.open_time) / pd.Timedelta(hours=1)

# create a column with timedelta as total duration_minutes, as a float type
# positions['duration_minutes'] = (positions.close_time - positions.open_time) / pd.Timedelta(minutes=1)

# create a column with timedelta as total duration_seconds, as a float type
positions['duration_seconds'] = (positions.close_time - positions.open_time) / pd.Timedelta(seconds=1)

positions

,open_time,magic,position_id,reason,volume,open_price,symbol,close_time,type,close_price,commission,swap,profit,fee,pnl,duration_seconds
0,2023-12-15 20:25:48,0,0,0,0.00,0.00000,,2023-12-15 20:25:48,balance,0.00000,0.0,0.00,10000.00,0.0,10000.00,0.0
1,2023-12-15 21:35:20,100,3818161067,3,0.01,1.08951,EURUSD,2023-12-15 21:35:34,buy,1.08932,0.0,0.00,-0.19,0.0,9999.81,14.0
2,2023-12-15 21:35:20,100,3818161068,3,0.02,1.08931,EURUSD,2023-12-15 21:35:33,sell,1.08952,0.0,0.00,-0.42,0.0,9999.39,13.0
3,2023-12-15 21:36:55,100,3818161079,3,0.01,1.26867,GBPUSD,2023-12-15 21:37:45,buy,1.26848,0.0,0.00,-0.19,0.0,9999.20,50.0
4,2023-12-15 21:36:55,100,3818161080,3,0.02,1.08929,EURUSD,2023-12-15 21:37:45,sell,1.08950,0.0,0.00,-0.42,0.0,9998.78,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2023-12-22 18:15:49,100,3818220792,3,0.01,1.10155,EURUSD,2023-12-22 18:40:51,buy,1.10155,0.0,0.00,0.00,0.0,9977.33,1502.0
63,2023-12-22 18:15:49,100,3818220793,3,0.05,1.10132,EURUSD,2023-12-22 18:40:51,sell,1.10175,0.0,0.00,-2.15,0.0,9975.18,1502.0
64,2023-12-22 18:16:29,100,3818220794,3,0.01,1.10151,EURUSD,2023-12-22 18:40:51,buy,1.10155,0.0,0.00,0.04,0.0,9975.22,1462.0
65,2023-12-22 18:16:29,100,3818220795,3,0.05,1.10131,EURUSD,2023-12-22 18:40:52,sell,1.10175,0.0,0.00,-2.20,0.0,9973.02,1463.0
66,2023-12-28 20:47:38,100,3818259693,3,0.01,1.10590,EURUSD,2023-12-29 11:31:30,buy,1.10489,0.0,-0.06,-1.01,0.0,9972.01,53032.0

In [473]:
# drop balance row in data frame
# positions = positions.drop(0)
positions.drop(index=[0], inplace =True)
display(positions)

,open_time,magic,position_id,reason,volume,open_price,symbol,close_time,type,close_price,commission,swap,profit,fee,pnl,duration_seconds
1,2023-12-15 21:35:20,100,3818161067,3,0.01,1.08951,EURUSD,2023-12-15 21:35:34,buy,1.08932,0.0,0.00,-0.19,0.0,9999.81,14.0
2,2023-12-15 21:35:20,100,3818161068,3,0.02,1.08931,EURUSD,2023-12-15 21:35:33,sell,1.08952,0.0,0.00,-0.42,0.0,9999.39,13.0
3,2023-12-15 21:36:55,100,3818161079,3,0.01,1.26867,GBPUSD,2023-12-15 21:37:45,buy,1.26848,0.0,0.00,-0.19,0.0,9999.20,50.0
4,2023-12-15 21:36:55,100,3818161080,3,0.02,1.08929,EURUSD,2023-12-15 21:37:45,sell,1.08950,0.0,0.00,-0.42,0.0,9998.78,50.0
5,2023-12-15 21:47:37,100,3818161113,3,0.01,1.26901,GBPUSD,2023-12-15 21:48:29,buy,1.26883,0.0,0.00,-0.18,0.0,9998.60,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2023-12-22 18:15:49,100,3818220792,3,0.01,1.10155,EURUSD,2023-12-22 18:40:51,buy,1.10155,0.0,0.00,0.00,0.0,9977.33,1502.0
63,2023-12-22 18:15:49,100,3818220793,3,0.05,1.10132,EURUSD,2023-12-22 18:40:51,sell,1.10175,0.0,0.00,-2.15,0.0,9975.18,1502.0
64,2023-12-22 18:16:29,100,3818220794,3,0.01,1.10151,EURUSD,2023-12-22 18:40:51,buy,1.10155,0.0,0.00,0.04,0.0,9975.22,1462.0
65,2023-12-22 18:16:29,100,3818220795,3,0.05,1.10131,EURUSD,2023-12-22 18:40:52,sell,1.10175,0.0,0.00,-2.20,0.0,9973.02,1463.0
66,2023-12-28 20:47:38,100,3818259693,3,0.01,1.10590,EURUSD,2023-12-29 11:31:30,buy,1.10489,0.0,-0.06,-1.01,0.0,9972.01,53032.0

In [474]:
# create profit type column (win / loss)

def apply_profit_type(x):
# Finding profit type
  if x['profit'] >= 0: 
      return "win"
  elif x['profit'] < 0:
      return "loss"
  else: return None

positions['profit_type'] = positions.apply(apply_profit_type, axis=1)

# positions.dropna(inplace=True)

display(positions)

,open_time,magic,position_id,reason,volume,open_price,symbol,close_time,type,close_price,commission,swap,profit,fee,pnl,duration_seconds,profit_type
1,2023-12-15 21:35:20,100,3818161067,3,0.01,1.08951,EURUSD,2023-12-15 21:35:34,buy,1.08932,0.0,0.00,-0.19,0.0,9999.81,14.0,loss
2,2023-12-15 21:35:20,100,3818161068,3,0.02,1.08931,EURUSD,2023-12-15 21:35:33,sell,1.08952,0.0,0.00,-0.42,0.0,9999.39,13.0,loss
3,2023-12-15 21:36:55,100,3818161079,3,0.01,1.26867,GBPUSD,2023-12-15 21:37:45,buy,1.26848,0.0,0.00,-0.19,0.0,9999.20,50.0,loss
4,2023-12-15 21:36:55,100,3818161080,3,0.02,1.08929,EURUSD,2023-12-15 21:37:45,sell,1.08950,0.0,0.00,-0.42,0.0,9998.78,50.0,loss
5,2023-12-15 21:47:37,100,3818161113,3,0.01,1.26901,GBPUSD,2023-12-15 21:48:29,buy,1.26883,0.0,0.00,-0.18,0.0,9998.60,52.0,loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2023-12-22 18:15:49,100,3818220792,3,0.01,1.10155,EURUSD,2023-12-22 18:40:51,buy,1.10155,0.0,0.00,0.00,0.0,9977.33,1502.0,win
63,2023-12-22 18:15:49,100,3818220793,3,0.05,1.10132,EURUSD,2023-12-22 18:40:51,sell,1.10175,0.0,0.00,-2.15,0.0,9975.18,1502.0,loss
64,2023-12-22 18:16:29,100,3818220794,3,0.01,1.10151,EURUSD,2023-12-22 18:40:51,buy,1.10155,0.0,0.00,0.04,0.0,9975.22,1462.0,win
65,2023-12-22 18:16:29,100,3818220795,3,0.05,1.10131,EURUSD,2023-12-22 18:40:52,sell,1.10175,0.0,0.00,-2.20,0.0,9973.02,1463.0,loss
66,2023-12-28 20:47:38,100,3818259693,3,0.01,1.10590,EURUSD,2023-12-29 11:31:30,buy,1.10489,0.0,-0.06,-1.01,0.0,9972.01,53032.0,loss

In [475]:
# find balance
balance = round(positions['pnl'].iloc[-1], 2)
print('balance = ', balance)

# find total net profit
total_net_profit = round(positions['profit'].sum(), 2)  # Use in backtest Factors
print('total net profit = ', total_net_profit)

# find gross profit
gross_profit = round(sum(positions[positions['profit_type']=='win']['profit']), 2)
print('gross profit = ', gross_profit)

# find gross loss
gross_loss = round(sum(positions[positions['profit_type']=='loss']['profit']), 2)
print('gross loss = ', gross_loss)

# find profit factor
profit_factor = abs(round((gross_profit / gross_loss), 2))
print('profit factor = ', profit_factor)

# find largest profit trade
largest_profit_trade = round(positions['profit'].max(), 2)
print('largest profit trade = ', largest_profit_trade)

# find largest loss trade
largest_loss_trade = round(positions['profit'].min(), 2)
print('largest loss trade = ', largest_loss_trade)

# find total trades
total_trades = len(positions)
print('total trades = ', total_trades)

# find total count of SELL trades
count_sell_trades = positions['type'].value_counts()['sell']
print('count SELL trades = ', count_sell_trades)

# find total count of BUY trades
count_buy_trades = positions['type'].value_counts()['buy']
print('count BUY trades = ', count_buy_trades)

# find total count of WIN trades
count_win_trades = positions['profit_type'].value_counts()['win']
print('count WIN trades = ', count_win_trades)

# find total count of LOSS trades
count_loss_trades = positions['profit_type'].value_counts()['loss']
print('count LOSS trades = ', count_loss_trades)

# select rows by value
# avg_win = deals_group.loc[deals_group['profit_type'] == 'win']
# print('avg_win' , avg_win)

# find average value of WIN Trades
ave_win_value = round(positions.loc[positions['profit_type'] == 'win']['profit'].mean() , 2)
print('ave_win_value = ' , ave_win_value)

# find average value of LOSS Trades
ave_loss_value = round(positions.loc[positions['profit_type'] == 'loss']['profit'].mean(), 2)
print('ave_loss_value = ' , ave_loss_value)

balance =  9972.01
total net profit =  -27.99
gross profit =  5.43
gross loss =  -33.42
profit factor =  0.16
largest profit trade =  5.2
largest loss trade =  -2.2
total trades =  66
count SELL trades =  23
count BUY trades =  43
count WIN trades =  7
count LOSS trades =  59
ave_win_value =  0.78
ave_loss_value =  -0.57

In [476]:
# Collect consecutive Profit / Loss (Factors)

# find consecutive Profit / Loss
positions_group = positions.groupby((positions.profit_type != positions.profit_type.shift()).cumsum()).agg(
  profit_type = ('profit_type', 'first'),
  grand_profit = ('profit', 'sum'),
  count = ('profit_type', 'count')
).reset_index(drop=True)

print('count trades groups = ')
print(positions_group)

# find largest consecutive WIN trade
largest_cons_win = round(positions_group['grand_profit'].max(), 2)
print('largest consecutive WIN trade = ', largest_cons_win)

# find largest consecutive WIN trade (count)
count_largest_win = positions_group.loc[positions_group['grand_profit'].idxmax(), 'count']
print('largest consecutive WIN trade (count) = ', count_largest_win)

# find largest consecutive LOSS trade
largest_cons_loss = round(positions_group['grand_profit'].min(), 2)
print('largest consecutive LOSS trade = ', largest_cons_loss)

# find largest consecutive LOSS trade (count)
count_largest_loss = positions_group.loc[positions_group['grand_profit'].idxmin(), 'count']
print('largest consecutive LOSS trade (count) = ', count_largest_loss)

count trades groups =
   profit_type  grand_profit  count
0         loss         -2.46      8
1          win          0.01      1
2         loss        -13.39     30
3          win          0.08      1
4         loss         -3.02      5
5          win          0.10      1
6         loss         -2.68      3
7          win          0.00      1
8         loss         -6.51     10
9          win          5.20      2
10        loss         -2.15      1
11         win          0.04      1
12        loss         -3.21      2
largest consecutive WIN trade =  5.2
largest consecutive WIN trade (count) =  2
largest consecutive LOSS trade =  -13.39
largest consecutive LOSS trade (count) =  30

In [477]:
# Such reports allow to compare different experts to each other in a quick mode. The following data are published in reports:

# Bars in test – the amount of the modeled history data in bars;
# Ticks modeled – the amount of the modeled ticks;
# Modeling quality – the quality of ticks modeled during testing in per cents. Modeling is schematically displayed as a band in the next line of the report. This band can be of one of three colors:
# Grey – this part of the data available was not tested at all. Grey color can appear, if the range of dates was given in tester settings;
# Red – modeling was not performed within this sub-range since no data of a smaller period were available. At that, only data from the period selected in the tester settings were used;
# Green – modeling was performed within this sub-range. At that, the brighter the color is, the better in quality the modeling was. For example, when testing at the period of H1, the dark-green band can mean that M30-period data were used for testing, and the brightest means that those of M1 period were used;
# Attention: If the fastest method ("by open prices") has been used for modeling in testing settings, the entire band will be red. At that, "n/a" – modeling has not been performed at all – will be written in the "Modelling quality" field;

# Initial deposit – the volume of the initial deposit;
# Total net profit – financial result of all trades. This index represents a difference between the "Gross profit" and "Gross loss";
# Gross profit – the sum of all profitable trades in terms of money;
# Gross loss – the sum of all unprofitable trades in terms of money;
# Profit factor – the ratio between gross profit and gross loss in per cents. The one value means that profit equals to loss;
# Expected payoff – the expected payoff. This statistically calculated index represents the average profit/loss factor of a trade. It can also be considered for representing the expected profit/loss factor of the next trade;
# Absolute drawdown – the largest loss is lower than the initial deposit value;
# Maximal drawdown (%) – maximal loss of the local maximum in the deposit currency and in percents of the deposit;
# Relative Drawdown – the maximal loss in percents of the maximum equity value and its corresponding money value;
# Total trades – the total amount of trade positions;
# Short positions (won %) – the amount of short positions and percentage of won thereof;
# Long positions (won %) – the amount of long positions and percentage of won thereof;
# Profit trades (% of total) – the amount of profitable trade positions and their percentage in the total trades;
# Loss trades (% of total) – the amount of loss trade positions and their percentage in the total trades;
# Largest profit trade – the largest profit among all profitable positions;
# Largest loss trade – the largest loss among all unprofitable positions;
# Average profit trade – average profit value for a trade (the sum of profits divided by the amount of profitable trades);
# Average loss trade – average loss value for a trade (the sum of losses divided by the amount of unprofitable trades);
# Maximum consecutive wins (profit in money) – the longest series of profitable trade positions and the sum of their wins;
# Maximum consecutive losses (loss in money) – the longest series of unprofitable trade positions and the sum of their losses;
# Maximal consecutive profit (count of wins) – the maximum profit of a series of profitable trades and the amount of profitable trades corresponding with it;
# Maximal consecutive loss (count of losses) – the maximum loss of a series of unprofitable trades and the amount of unprofitable trades corresponding with it;
# Average consecutive wins – the average amount of profitable positions in consecutive profitable series;
# Average consecutive losses – the average amount of unprofitable positions in consecutive unprofitable series.
# This report can be copied to the clipboard or saved in the hard disk as an HTML file. To do so, one has to execute the "Copy" context menu command or that of "Save as Report", respectively. The report can also be copied to the clipboard by pressing of accelerating keys of Ctrl+C.